In [2]:
import numpy as np

a = np.random.randn(5) #不是一个矩阵

In [3]:
print(a)

[ 0.04053977 -0.76783849  0.33457505 -0.27406032 -0.88311044]


In [4]:
print(a.shape) #秩为一的数组（不要使用！用行列向量代替）

(5,)


In [5]:
print(a.T)

[ 0.04053977 -0.76783849  0.33457505 -0.27406032 -0.88311044]


In [6]:
print(np.dot(a,a.T)) #按理说是向量外积，答案却是内积

1.558152990107819


In [7]:
a = np.random.randn(5,1)#是一个列向量（矩阵）
print(a)

[[ 0.4334474 ]
 [-1.80450891]
 [-0.76067323]
 [ 0.39411087]
 [ 0.55752632]]


In [8]:
print(a.T)

[[ 0.4334474  -1.80450891 -0.76067323  0.39411087  0.55752632]]


In [9]:
print(np.dot(a,a.T))#向量外积

[[ 0.18787665 -0.7821597  -0.32971183  0.17082633  0.24165834]
 [-0.7821597   3.25625241  1.37264162 -0.71117657 -1.00606122]
 [-0.32971183  1.37264162  0.57862376 -0.29978958 -0.42409535]
 [ 0.17082633 -0.71117657 -0.29978958  0.15532337  0.21972718]
 [ 0.24165834 -1.00606122 -0.42409535  0.21972718  0.3108356 ]]
